const IMAGE_SETTING = "IMAGE_SETTING";
const TEXT_SETTING = "TEXT_SETTING";
const SOUND_SETTING = "SOUND_SETTING";
const CONTROLLER_SETTING = "CONTROLLER_SETTING";
const INGAME_SETTING = "INGAME_SETTING";

module.exports = {
	IMAGE_SETTING,
	TEXT_SETTING,
	SOUND_SETTING,
	CONTROLLER_SETTING,
	INGAME_SETTING
}


//这都是些傻逼保留字，没什么用的。