const GET_NOW_PLAYING_SECTION = 'GET_NOW_PLAYING_SECTION';
const SET_NOW_PLAYING_SECTION = 'SET_NOW_PLAYING_SECTION';
const ENTER_NEXT_CHAPTER = 'ENTER_NEXT_CHAPTER';
const ENTER_NEXT_SECTION = 'ENTER_NEXT_SECTION';
const ENTER_PREV_CHAPTER = 'ENTER_PREV_CHAPTER';
const ENTER_PREV_SECTION = 'ENTER_PREV_SECTION';
const MAKE_SELECTION = 'MAKE_SELECTION';
module.exports = {
    GET_NOW_PLAYING_SECTION,
    SET_NOW_PLAYING_SECTION,
    ENTER_NEXT_CHAPTER,
    ENTER_NEXT_SECTION,
    ENTER_PREV_CHAPTER,
    ENTER_PREV_SECTION,
    MAKE_SELECTION
};

    //define some constraint.