
const GET_ALL_CHAPTERS = 'GET_ALL_CHAPTERS';
const SET_ALL_CHAPTERS = 'SET_ALL_CHAPTERS';
const GET_NOW_PLAYING_SECTION = 'GET_NOW_PLAYING_SECTION';
const SET_NOW_PLAYING_SECTION = 'SET_NOW_PLAYING_SECTION';
const GET_SELECTED_PLAYING_SECTION = 'GET_SELECTED_PLAYING_SECTION';
const SET_SELECTED_PLAYING_SECTION = 'SET_SELECTED_PLAYING_SECTION';
const ENTER_NEXT_CHAPTER = 'ENTER_NEXT_CHAPTER';
const ENTER_NEXT_SECTION = 'ENTER_NEXT_SECTION';
const ENTER_PREV_CHAPTER = 'ENTER_PREV_CHAPTER';
const ENTER_PREV_SECTION = 'ENTER_PREV_SECTION';
const MAKE_SELECTION = 'MAKE_SELECTION';
const NEXT_NODE = 'NEXT_NODE';
const PREV_NODE = 'PREV_NODE';
const SET_NODE_INDEX = 'SET_NODE_INDEX';
const NOW_LOADING = 'NOW_LOADING';
const LEAVE_GAMEVIEW = 'LEAVE_GAMEVIEW';
const INTERNAL_ERROR = 'INTERNAL_ERROR';

module.exports = {
    GET_NOW_PLAYING_SECTION,
    SET_NOW_PLAYING_SECTION,
    ENTER_NEXT_CHAPTER,
    ENTER_NEXT_SECTION,
    ENTER_PREV_CHAPTER,
    ENTER_PREV_SECTION,
    MAKE_SELECTION,
    GET_ALL_CHAPTERS,
    SET_ALL_CHAPTERS,
    NEXT_NODE,
    PREV_NODE,
    SET_NODE_INDEX,
    GET_SELECTED_PLAYING_SECTION,
    SET_SELECTED_PLAYING_SECTION,
    INTERNAL_ERROR,
    NOW_LOADING,
    LEAVE_GAMEVIEW
};
