import GameView from './GameView/GameView';
import AllChapterView from './AllChapter/AllChapterView';
import Scene from './Scene/Scene';
//import TextBox from './TextBox/TextBox';
import CustomView from './CustomView/CustomView';
import NewTextBox from './TextBox/NewTextBox';
import Loading from './Loading/Loading';
import { Settings } from './Settings/index';
import Selection from './Selection/Selection';
import SaveDataView from './SaveData/SaveDataView';
import PlainText from './PlainText/PlainText';
import WelcomeView from './Welcome/WelcomeView';
import Character from './Character/Character';
import Backlog from './Backlog/Backlog';
export { GameView, AllChapterView, Scene,CustomView, Loading, Settings, WelcomeView, PlainText,SaveDataView,Selection ,NewTextBox,Backlog,Character};